name: claim
description: "TP Claim"
publish_to: 'none'

version: 2.0.5+11

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  fluentui_system_icons: ^1.1.273
  line_icons: ^2.0.3
  ionicons: ^0.2.2
  image_picker: ^1.0.7
  camera: ^0.10.5+9
  intl: ^0.18.1
  mobile_scanner: ^7.0.0
  simple_barcode_scanner: ^0.3.0
  shared_preferences: ^2.5.3
  http: ^1.1.0
  dartz: ^0.10.1
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  image: ^4.1.3
  qr_flutter: ^4.1.0
  package_info_plus: ^8.0.0
  # flutter_barcode_scanner: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1 

flutter:
  uses-material-design: true
  assets: 
    - assets/images/TP.png
    - assets/images/tpicon.png
    - assets/images/TP1.png
    - assets/images/TP2.png
    - assets/images/TP3.png
    - assets/images/profile.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/TP.png"
